stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preprocess:
    cmd: python src/data_preprocess.py
    deps:
    - data/raw
    - src/data_preprocess.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed
    - src/feature_engineering.py
    outs:
    - data/vectorized
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/vectorized
    - src/model_building.py
    outs:
    - models/xgb_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - data/vectorized
    - models/xgb_model.pkl
    metrics:
    - results/evaluation_metrics.json
